### ISSUE TITLE
Be transparent about what happens to comments

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/makers.bolt.fun#106]
Problem
- We distribute comments on nostr but no one is aware of this from looking at the UI
- Since we create an identity on nostr (generate a private key and store it in our database) the user doesn't have access to their "account" or any of the data

Solution
- Show connected relays and some information about what happens to comment data
- Allow someone to view their Nostr private key so they can import it into another client

**Comment by MTG2000** [comment]
@johnsBeharry 
where would be the best place to do that??
I feel that this could be a section in the user's profile, where he can manage his keys, copy them, or even put his own keys if we want to enable that.
Especially because these keys are probably going to be used in more places than comments later.

**Comment by johnsBeharry** [comment]
> I feel that this could be a section in the user's profile, where he can manage his keys, copy them, or even put his own keys if we want to enable that.

#### `Comments (experimental)`
_Our commenting system is experimental and uses Nostr to store and relay your messages and replies to our own relay, as well as relays ran by other people in the community. We generate Nostr keys for you since there are no popular wallets which support it._

1. Click here to request your Nostr keys
2. Connect your Nostr identity (coming soon)
3. See list of relays

**Comment by MTG2000** [comment]
And we can do that also with the relays.
We can have a section that shows what are the relays that we are using (our default relay)
And maybe we can later allow the user to add extra relays that will be used when he post/query nostr data.

**Comment by MTG2000** [comment]
> 2\. Connect your Nostr identity (coming soon)

By this you mean allowing him to put his own private nostr key??

**Comment by johnsBeharry** [comment]
> By this you mean allowing him to put his own private nostr key??

No, if someone has [the Nostr extension](https://github.com/fiatjaf/nos2x) then we can do this

```
let publicKey = async window.nostr.getPublicKey()
let verifyKeyOwner = async window.nostr.signEvent({msg: publicKey})
```

Then when people post comments, instead of calling our API for signing messages using the key we generated in our database, we instead call `window.nostr` instead.

**Comment by barefoot-88** [comment]
## Designs

### Discussion component
For this component, we are adding a toast component that will lead to a story outlining the way Nostr comments work, how data is stored, and how to find your keys, relays, etc in the users Settings menu. 

We can also add a badge component that shows the following states to signify the Nostr connection status:
**Green** = Connected to X relays
**Amber** = Connecting to relays
**Red** = Not connected

<img width="1327" alt="Screenshot 2022-07-29 at 10 41 36" src="https://user-images.githubusercontent.com/36778205/181732056-643af327-d0b9-4e13-908e-a2fe16c2a2e7.png">

<img width="1304" alt="Screenshot 2022-07-29 at 10 42 28" src="https://user-images.githubusercontent.com/36778205/181732201-8a05c650-21fc-4cea-820f-529e607c947e.png">

<img width="1185" alt="Screenshot 2022-07-29 at 10 43 35" src="https://user-images.githubusercontent.com/36778205/181732420-b8f2bd5d-573d-42d8-8ea6-3cce54a0eb2d.png">


### Nostr Comments (Profile)
As discussed, we will also add a component to the users profile (edit state) which allows them to discover more about Nostr comments, how to find their keys, relays, and more. Please find out more about this edit state in Issue #

<img width="1058" alt="Screenshot 2022-07-29 at 11 06 54" src="https://user-images.githubusercontent.com/36778205/181736652-21777a0c-b689-4e4f-9b0a-fc228c52ea04.png">

**Comment by johnsBeharry** [comment]
Going to close this issue because a solution has been deployed already in #100
