### ISSUE TITLE
Redesign the edit state of maker profiles

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#108]
## Issue
At the moment, maker profiles are very basic and allow users to edit their static profile data (e.g Name, description, etc). However, this will change in the coming months as we begin to add more **static*** and **dynamic*** information to the maker profile.

**Static information*:** Information that is attached to a maker profile does not regularly change. These are things like Name, Lightning Address, Avatar, Description, Timezone, Job Role, etc.
**Dynamic information*:** Information that is added to a maker profile over time as they become more active on the platform. These include Stories, Activity, Badges, Products (semi-dynamic as won't change too often). 

## Solution
As the maker profile becomes more complex and rich in data, makers will need a way to navigate the various elements of their profile - editing or viewing any information. For this to happen, I'd like to introduce a side navigation when the user accesses their profile's edit state. This state can be accessed by either:

- Going to their profile and clicking "Edit profile" button on their main profile card
- When the user clicks their avatar in the main page navigation bar (top right hand corner), a dropdown menu appears reading: Profile | Settings | Logout. If the user clicks "Settings", it should take them to the edit state of their profile. See #107 

Once the user sees the edit state of their profile, the page should be structure using our 3 column grid layout (same in Stories, etc). 
 
**Left column** ⬅️
User sees a page navigation card reading **"Edit maker profile"** with the menu options of **"👾 My profile"** (giving the edit access to their maker profile information) and **"⚙️ Preferences"** (giving them access to extra settings like Nostr comments, and later more). This card should be fixed to the top of the page when scrolling so the user can navigate between pages at any time.

**Centre column** ⬆️
In the centre column is the bulk of information shown as the user navigates through the various section of their profile and its settings. If the user has selected **👾 My profile** then it will show a card containing their profile information, if they've selected **⚙️ Preferences**, it will show a card outlining Nostr comments (v1), later to add more preferences and settings features (e.g Appearance, Notifications, etc).

**Right column** ➡️
In the right hand column is a card containing a preview state of the maker's profile (Avatar, name, job role, and description). Below this information is a **Save Changes** and **Cancel** CTAs. This card should be fixed to the top of the page when scrolling so the user can click "Save changes" at any time.

### Web view
**👾 My profile**
<img width="726" alt="Screenshot 2022-07-29 at 11 50 37" src="https://user-images.githubusercontent.com/36778205/181744126-653fe30e-9465-4593-bb88-c7af2b678fd1.png">

**⚙️ Preferences**
<img width="985" alt="Screenshot 2022-07-29 at 11 50 50" src="https://user-images.githubusercontent.com/36778205/181744160-5ca71ea7-6207-4a52-a88b-f7c1a826cedd.png">

### Mobile view
<img width="625" alt="Screenshot 2022-07-29 at 11 51 17" src="https://user-images.githubusercontent.com/36778205/181744229-7c64b386-f8b8-4662-a6c8-a3cfd41a95ff.png">

**Comment by johnsBeharry** [comment]
hey @barefoot-88 why are there two save button groups?

<img width="301" alt="Screenshot 2022-07-29 at 18 31 37" src="https://user-images.githubusercontent.com/183140/181804061-282bc00e-bdb2-4ad7-b300-41d195b37006.png">

**Comment by barefoot-88** [comment]
> hey @barefoot-88 why are there two save button groups?
> 
> <img alt="Screenshot 2022-07-29 at 18 31 37" width="301" src="https://user-images.githubusercontent.com/183140/181804061-282bc00e-bdb2-4ad7-b300-41d195b37006.png">

Thanks for spotting. We can remove the save button group on the profile card in that case. Makes sense to have them in the right column so it can fix position during scroll and users can save at any point.

**Comment by johnsBeharry** [comment]
ye I like it on the right.

**Comment by MTG2000** [comment]
A small question @barefoot-88 
Is the save button on the right going to save changes across all the sections that the user made changes to??
I mean he may open his "Profile" section and change something, then open another section and change another thing.
If he press "Save changes" now, will it save his changes across all the sections??

**Comment by barefoot-88** [comment]
@MTG2000 

> A small question @barefoot-88 Is the save button on the right going to save changes across all the sections that the user made changes to?? I mean he may open his "Profile" section and change something, then open another section and change another thing. If he press "Save changes" now, will it save his changes across all the sections??

I believe it would, yes. One save button to rule them all. If they click save, it will ofc take them back to the un-edited state of their profile.

**Comment by MTG2000** [comment]
@barefoot-88 
Ah, okays.

Having a single 'save changes' button has its benefits indeed.

At the same time (and I might be wrong), I feel that keeping a 'save' button for each section has a little more benefits.

Mainly, when the user save his changes, he know exactly what he changed because they are in front of his eyes as opposed to these changes being in another hidden tab.
Secondly, showing validation errors for each page.
Thirdly, it's better to handle the case where some changes on some page may not successed for whatever reason, so we don't want to revert all the other changes that would have been saved successfully.

This approach is common in many sites like Gmail for example, where each settings page has its own save changes button.
Or linkedin, where each section has its edit-in-place section and save btn.

**Comment by barefoot-88** [comment]
Hmm. The Google & Linked-In examples seems to be more useful as they separate out the sections a bit more, rather than giving users the ability to make multiple changes in bulk. But maybe I didn't see the write journey, do you have screenshots you can share?

Personally, I think editing in bulk should be ok... but open to discussion @johnsBeharry

**Comment by johnsBeharry** [comment]
Perhaps we can do a design review for this?

**Comment by MTG2000** [comment]
> do you have screenshots you can share?

![image](https://user-images.githubusercontent.com/50504183/182385917-bcaabdbc-3325-421b-bf22-50fb5a9510ba.png)
Here on linkedin, you can see that each section has its own edit modal/page and a save changes for each one.

The same for gmail settings.
Each tab has it's own (Save/cancel) actions
![image](https://user-images.githubusercontent.com/50504183/182386593-79b890ff-5e56-43ea-9ef5-cdc3c940d118.png)

**Comment by barefoot-88** [comment]
**Left Column** (Navigation) 
- My profile (any information relating to the users profile)
- Settings & Preferences (Nostr, Linked Accounts, etc)

_**This component is sticky whilst the user scrolls.**_

**Middle Column** (Information)
- Selected page cards showing information (sometimes editable)

**Right Column** (Profile Preview + Save) - Sticky!
- Profile preview (Avatar, Name, Description, Role)
- CTAs (Save Changes, Cancel)

_**This component is sticky whilst the user scrolls.**_

If the user clicks Save Changes, the button shows a loading state. We then pop up a success message saying the changes have successfully been made to the profile. 

<img width="1046" alt="Screenshot 2022-08-10 at 09 37 54" src="https://user-images.githubusercontent.com/36778205/183855780-2e200697-c70b-4009-85c3-2d62a1bc1c4c.png">

**Comment by barefoot-88** [comment]
**Saving changes**
For saving changes, we want to avoid certain user errors:
- Confusion when saving multiple batch changes
- Batched saves failing due to one error on another tab... 

To solve this issue, we can still use the right column buttons, however the way the user interacts with them lets them know that:
a). Changes have/have not been made on a page (disabled -> Enabled states)
b). If the user makes unsaved changes changes and tries to navigate to another tab, we can show a message saying "Make sure to save your changes before continuing."

**Comment by barefoot-88** [comment]
<img width="1251" alt="Screenshot 2022-08-10 at 09 54 47" src="https://user-images.githubusercontent.com/36778205/183859504-064ca1f4-4860-415d-9cf8-f896467b34b0.png">
