### ISSUE TITLE
Allow makers to add new products

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#109]
## Issue
ATM, makers are unable to list products themselves. This leads to a backlog of data we have to manually manage on the backend. It's also not a scalable approach for moving forward.

## Solution
We should allow makers to add new products to BOLT🔩FUN. This involves designing and developing a new user journey, **List a product** 🚀

**Left column** ⬅️
User sees a page navigation card reading "List your product" with the menu options of 🚀 Product details, ⚡️ Team, and 💎Extras. This card should be fixed to the top of the page when scrolling so the user can navigate between pages at any time.

**Centre column** ⬆️
In the centre column is the bulk of information shown as the user navigates through the various section of their List your product flow.

**Right column** ➡️
In the right hand column is a card containing a preview state of the product (Avatar, name, and one-liner). It could also show a progress bar. When the user reaches the final page (Extras), the main CTAs (List your product + Save for later) show up and remain. We could also show a "Saved" card which could be for products a maker hasn't launched but wants to come back to and edit/delete/launch.

### User journey
The journey for adding a new product is split up into 3 different sections. As the user progresses through the following sections, the CTA is "Next step: {section}", encouraging them to complete all the necessary information and fill out their product profiles as much as possible. It also creates a linear feel to the journey. Once they reach the final section, the preview card (right column) shows CTAs for either "List product" or "Save for later" (if they wish to launch the product at a later date). 

**🚀 Product details**
This is where makers upload the main bulk of required details to list their product. E.g Name, website/link, description, one-liner, screenshots, capabilities, category, etc.

**⚡️ Team**
The maker selects if they worked on the project or not. If they did, they can list other team members by searching their maker profile handles/names. If not, the "add team" section is hidden.

**💎 Extras**
These extras include Launch status (Launched vs WIP), Shock the Web submission info, and adding a Comment. Once the user reaches this screen, the main CTAs (Launch or Save for Later) show up and now remain constant even if they navigate back to other pages (e.g Product details, Team).

### Web
**🚀 Product Details**
<img width="819" alt="Screenshot 2022-07-29 at 13 31 33" src="https://user-images.githubusercontent.com/36778205/181758889-724c6366-6eb4-402b-85e4-50748f7d3c06.png">

**⚡️ Team**
<img width="1656" alt="Screenshot 2022-07-29 at 13 31 53" src="https://user-images.githubusercontent.com/36778205/181758947-40a2aaf6-300f-4179-801d-97887b0882cb.png">

<img width="1640" alt="Screenshot 2022-07-29 at 13 32 13" src="https://user-images.githubusercontent.com/36778205/181758996-c62bb9c3-bbfc-4e4c-916c-366ee66bbe34.png">

**💎 Extras**
<img width="1418" alt="Screenshot 2022-07-29 at 13 32 36" src="https://user-images.githubusercontent.com/36778205/181759086-f758fd67-0452-4143-a2df-d78f4975afb1.png">

### Mobile
<img width="495" alt="Screenshot 2022-07-29 at 13 48 07" src="https://user-images.githubusercontent.com/36778205/181763777-2729805e-ff96-4b10-bb2a-42d06542d61b.png">

**Comment by johnsBeharry** [comment]
Note: Changing name from: Products -> Projects 

1. With tournaments being developed next we will need to accommodate things beyond web applications in order to cater for a more mainstream maker community which that opportunity presents us with
2. There has been interest in having initiatives (bounties, hackathons, or tournaments) which promote the creation of developer tools
3. Some makers might be interested in building mobile applications

**Comment by barefoot-88** [comment]
@MTG2000 Please see all the updated designs and components in this Figma file: https://www.figma.com/file/2rWlc79smZ9oyWSZHKhUUy/BOLT%F0%9F%94%A9FUN?node-id=1701%3A91750

I have designed both web + mobile. 

Any questions LMK.

**Comment by MTG2000** [comment]
@barefoot-88 
question:
Is there a limit for how many capabilities a maker can choose for a project??

**Comment by MTG2000** [comment]
@barefoot-88 

Regarding the user's journey, I'd like to ask you about a few points.
First things first, we know that this section will be used in 2 journeys.
1- Listing a new project.
2- Updating some info in an already created project.

So what are the differences between the two?
I think the differences mainly are:
- The CTAs
- where/when we actually make the save changes request
- and maybe whether jumping between the tabs is allowed

So for the 1st journey (Inserting new):
- The CTAs should be as you said above. So (Next, Next, Launch)
- The saving request happens only at the end, when the user clicks "Launch".
But when clicking "Next" on any page, if there are any errors, they will immediately be shown before moving the user to the next page.
- Jumping between the tabs should probably not be allowed.
(Cause would a user really wants to fill his team members first before filling his project name/website/tagline...etc)
So maybe we can either hide the tabs list in the sidebar, or show the next steps in a disabled state, but maybe the previous one can be navigated back to.

For the 2nd journey (Updating an existing one):
- The user may want to update only one thing on one tab, so the CTA on each tab should be "Save Changes".
- The saving request happens on any page that the user make changes on then hit "Save Changes".
- Jumping between the tabs is allowed.

I'd like to hear your thoughts about this.

**Comment by barefoot-88** [comment]
Hey @MTG2000 , here are a few answers to your questions ... 

a). Capabilities limits: not entirely sure. @johnsBeharry any thoughts? Initially I'm thinking no limits. But if we do, maybe 3?

b). User journey. You're right about the journeys being slightly different between "Add Product" and "Edit Product". 

**Add product**
- CTAs should be Next, Next, Launch... 
- I disagree regarding the navigation. Users like to explore, so let's let them explore. Id personally like to flick between tabs and see what info I need before committing to the entire journey...  The only information which is **required** is the Product Details card (Photo, name, link, short + long description). Everything else is optional... 
- If the user fails to submit the required info (above), we only need to send them back to one section of the journey... so it's not the end of the world for this error state and I don't think we need to be overly controlling about the navigation. Check out Product Hunt and try submitting/launching a product, their journey gives the user freedom but is clearly structured. The difference is they have a "launch checklist" at the end where the user can see what more is required from them and they can click back to that section... 
- For all of the above, I think an auto save function should be enabled.. or at least we don't use the "Next" button as a save feature. This means if the user does flick between tabs they don't lose progress...

**Comment by johnsBeharry** [comment]
@MTG2000 @barefoot-88 no limits to the capabilities.

**Comment by MTG2000** [comment]
Hey @barefoot-88 

I see your point.
Yeah, implementing this functionality is a bit tricky and will take a little more time than the standard one.
But it's definitely doable, so I'll do it 👍
