### ISSUE TITLE
Create logged-out state for comments 💬

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#114]
## Issue
At the moment, if a user is logged out of their account (or has not yet created one), the Discussion section shows comments but no CTA of how to start commenting.

<img width="969" alt="Screenshot 2022-08-03 at 14 40 04" src="https://user-images.githubusercontent.com/36778205/182622350-4b5090e2-db76-4a18-9aa8-69dfdf80ee6b.png">

### Option 1
If the user is not yet authenticated, the toast that currently shows should be replaced with one that says, "Connect with lightning to use this feature." If the user clicks the link, it should open up the login widget. Once the user is connected, it shows the standard authenticated state of the Discussion component.

The downside of this option is that we should online display one toast at a time. So if the user logs in, and the toast is immediate replaced with the "Learn about Nostr" one, it might cause some confusion, or they might be more inclined to close it and get it out of sight.

<img width="908" alt="Screenshot 2022-08-03 at 14 49 43" src="https://user-images.githubusercontent.com/36778205/182624686-eb994fa0-f5dd-430c-9a2b-fc23bbc8313d.png">

### Option 2
A more favourable solution would be to replace the "Submit" button with "Connect to comment ⚡️" one. The avatar displayed could be a blank/gray one to signify there is no user logged in. See Product Hunt's example below, as well as how we could implement it ourselves.

The downside of this option might be that a user types out a response and hits the button, not realising they have to login. If they then go through the authentication journey, will their comment be saved or will they have to type it out again?

**Product Hunt**
<img width="830" alt="Screenshot 2022-08-03 at 14 42 37" src="https://user-images.githubusercontent.com/36778205/182622969-b6998b9c-da8b-4c11-bf7f-0c9a6c670794.png">

<img width="859" alt="Screenshot 2022-08-03 at 14 50 23" src="https://user-images.githubusercontent.com/36778205/182624820-aa3e69e8-ce66-498b-aefe-d16fb29a15f1.png">

**Comment by MTG2000** [comment]
I've implemented a solution similar to the second one, but the "Connect" button will appear on top of the comments editor and blurred a little, so that he will first go connect his profile first, and then I automatically redirect him to the article page.

![image](https://user-images.githubusercontent.com/50504183/182835669-fe05eba6-ec5f-458f-970b-f788ecae75bf.png)

**Comment by barefoot-88** [comment]
Ok, this will work for now. Was there a particular reason we went with this design decision?

**Comment by MTG2000** [comment]
Feel free to suggest any changes.

I went with it this way cause as I said, it's close to the 2ed option, which you (and me) like more than the first 1.
But it won't be very easy (and pleasent) to allow the user to write the comment, then save it temp, then send him to the login page, and later restore it (or automatically send it).

**Comment by MTG2000** [comment]
If you want to have it look different (but for now let's stick with no-writing-before-login).
Then just send that to me & I'll implement them.

**Comment by barefoot-88** [comment]
Ok cool, just wanted to check if it was because it was difficult to implement the saved comment changes etc.  Interestingly, I just completed the same journey on Product Hunt... 

- Write comment
- Click "Login to Comment button"
- Go through Login flow
- Takes user back to home page
- Clicked on same product and the comment was still there, saved

Whilst I'm glad I didn't write it out twice, I was left wondering if the comment was posted or not... 

So yeah, think there's a better solution somewhere out there! Let's go with what you've done for now as it's more important we implement something for the time being, and like you said saves the headache of the issues with Option 2!

Apologies if it came across as pedantic, just want to make sure we have back-and-forth discussion regarding changing designs so we're on the same page ❤️

**Comment by MTG2000** [comment]
Yeah sure, no worries man ❤

I should have talked about the approach that I was going to implement before implementing it, so that we could discuss it if needed to.

So will make sure to do that going forward 👍

**Comment by barefoot-88** [comment]
> Yeah sure, no worries man ❤
> 
> I should have talked about the approach that I was going to implement before implementing it, so that we could discuss it if needed to.
> 
> So will make sure to do that going forward 👍

All good ❤️ I'm still learning about these processes too, just thought I'd flag for future! Nice work on the implementation though
