### ISSUE TITLE
Error during saving a story with multiple images

### ISSUE THREAD

**Issue by reneaaron** [peakshift/makers.bolt.fun#115]
### Steps to reproduce

1. Create a post with multiple images 
2. Click "Save as draft"
3. See an error and the post hasn't been saved
![image](https://user-images.githubusercontent.com/100827540/182792270-4bbaec88-1f3a-48cb-a12d-ff6f0db443b8.png)

### Analysis

![image](https://user-images.githubusercontent.com/100827540/182792413-e514ad99-112a-4146-860c-b33a78cb83c8.png)

I somehow expect the total filesize of the images embedded in the story to cause this problem as uploading & saving the story worked with only 1 image embedded.

**Comment by MTG2000** [comment]
Hey Rene.
First thing, I want to thank you for including the inspection error message 🙏

That's a weird error actually....
May I ask you how are you uploading the images??
Are you including a URLs for images hosted on some images-service??
Or are you for example embedding the images data directly in the post body??

**Comment by reneaaron** [comment]
I added them to the editor post body via copy & paste like here:

https://makers.bolt.fun/blog/post/story/56/lightning-payment-links-on-the-web

The limit seems to be around ~1MB of content. Given you want to embed some screenshots that could be a bit low, right?

**Comment by MTG2000** [comment]
Ah, I see.

Yeah, we were not intending for images to be embedded directly in the post page.
They are supposed to be uploaded on some images-hosting-service, and then only the URL is included.

Currently, we don't have an images-hosting-service yet, but that's definitely something that we will add soon.
So you won't need to put the images data directly in the post body.

We have an issue opened for that #77, so hopefully it get resolved soon.

**Comment by reneaaron** [comment]
Got it, thanks. I will just go ahead an migrate those inline images to imgur. Thanks for the quick feedback! 💯
