### ISSUE TITLE
Markdown URLs do not escape trailing period

### ISSUE THREAD

**Issue by secondl1ght** [peakshift/makers.bolt.fun#119]
If you write a URL in a stories post it will be detected as a link, however if you end the sentence including the link with a period '.' it will be included in the link URL and break the path. See below:

![image](https://user-images.githubusercontent.com/85003930/183298449-1a2b4efd-c6ed-41b0-ac4c-e62f12fedee1.png)

**Comment by MTG2000** [comment]
Hey @secondl1ght 

Thanks for pointing that out.
Yeah, the auto linking feature isn't always correct, and sometimes it's automatically including parts in the url that shouldn't be like a period.

To solve that, I've added an 'insert link' to the toolbar that can be used in cases where the auto-linking can't detect the link correctly.
It's now in the staging version, and should be deployed to production soon.

**Comment by secondl1ght** [comment]
awesome thanks, thats a good solution!

**Comment by barefoot-88** [comment]
Agreed re: the 🔗 'insert link' button in the markdown toolbar. Thanks for flagging this issue @secondl1ght
