### ISSUE TITLE
Edit Story's "Discussion" on mobile

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#120]
## Issue
ATM the Discussion section sits within a card with 24px padding. Having this element within a card on mobile eats up a lot of valuable screen space.

<img width="409" alt="Screenshot 2022-08-08 at 10 33 40" src="https://user-images.githubusercontent.com/36778205/183387346-b706a1d8-a932-400d-9f97-62615b1b0fd9.png">

## Solution
Remove the card (and padding) surrounding this component, breathing room back into the Discussion section.

<img width="287" alt="Screenshot 2022-08-08 at 10 34 25" src="https://user-images.githubusercontent.com/36778205/183387521-d874bbb5-0d3a-4447-8532-4c1df721b67a.png">

## Also...
Can we move the "Trending on BOLT🔩FUN" card below the discussion? The discussion is a more important element and should come first. We can also remove the card around this element too on mobile.

**Comment by johnsBeharry** [comment]
@barefoot-88 comparing how this component would change within our design system, and not only in use is an important thing to communicate on this issue also. when you get a chance please explore this.
