### ISSUE TITLE
projectId is not correctly passed for voting requests

### ISSUE THREAD

**Issue by bumi** [peakshift/makers.bolt.fun#14]
It seems currently a hard coded `1` is used as `projectId`
https://github.com/peakshift/makers.bolt.fun/blob/5e677cbce1a2af39dc381d5b4a0c7beec7ab5659/src/pages/ProjectPage/Tip/TipCard.tsx#L123

this means all votes are counted for project#1

**Comment by MTG2000** [comment]
oh crap.
I fixed it now.
