### ISSUE TITLE
Define Roles & Skills 🎛 🌈

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#142]
Makers will soon be able to add **Roles** and **Skills** to their profiles. We need to come up with a list of both so that makers can preselect them.

## Roles 🎛
- 💄 Frontend Dev
- 💻 Backend Dev
- 🌈 UI/UX Designer
- 🎉 Community Manager
- 🦄 Founder
- 🚨 Marketer
- 🎥 Content Creator
- 🔬 Researcher
- 💿 Data Engineer
- 📈 Growth Hacker
- ✍️ Writer

### Design
- Wireframing
- Prototyping
- UI design
- UX design
- User testing
- User research
- Illustration
- Graphic design
- Figma
- Principle
- Miro
- Website design
- Logo design

### Engineering
- Wordpress
- Frontend
- Backend
- Python
- Javascript
- Vue.js
- React.js
- CSS
- HTML
- Markdown
- GraphQL

... @MTG2000 thoughts...? 💭

### Project Management
- Github
- Trello
- ClickUp
- Storybook
- Task management

**Comment by johnsBeharry** [comment]
@barefoot-88 we should open this up to the community. especially wrt to design skills too.

**Comment by MTG2000** [comment]
@johnsBeharry 
Or maybe we can add a small link at the end of the card with content similar to:
"Can't find a skill here, you can request that _**here**_"
And this "here" can be a link to: this GH issue/google doc/discord channel/...etc
Where they can place their request.

**Comment by johnsBeharry** [comment]
That's a good idea too. I'd say we do both. It's good to have users and community involved in some of the design process - even if just for feedback so we can validate / gauge if something is required. It'll be slow to pick up but we should continue to create those opportunity for people to join in.

**Comment by MTG2000** [comment]
@barefoot-88 
Here is an initial list for engineering skills that we can add:

## Engineering
* HTML/CSS
* JavaScript
* TypeScript
* React.Js
* Vue.Js
* Angular.Js
* jQuery
* Wordpress
* GraphQl
* Node.Js
* PHP
* .Net
* Python
* Java
* C++
* SQL
* NoSQL
* Git
* Testing

And adding new skills is relatively an easy task.
Cause anyone can do that from the DB admin page.

**Comment by johnsBeharry** [comment]
💡 Would be cool if we could have a json file that people could create pull requests for and have it update the DB.
