### ISSUE TITLE
Are the latest resolver functions deployed?

### ISSUE THREAD

**Issue by bumi** [peakshift/makers.bolt.fun#15]
It seems there is a bug with counting votes which should be resolved in master. Are the latest functions deployed? And if so are we sure those are called?

**Comment by bumi** [comment]
I cam imagine that this is the wrong URL: https://github.com/peakshift/makers.bolt.fun/blob/18beaf0f39fe86a4fc4ca45b91bf052bfdeb11eb/src/utils/Wrapper.tsx#L18

**Comment by bumi** [comment]
I don't know how/where this app here is deployed

**Comment by bumi** [comment]
probably https://makers.bolt.fun/.netlify/functions/graphql ?

**Comment by MTG2000** [comment]
> probably https://makers.bolt.fun/.netlify/functions/graphql ?

I noticed this, but when I tried to run queries on it, it's throwing errors:


{
  "errors": [
    {
      "message": "\nInvalid `context.prisma.project.findMany()` invocation in\n/var/task/functions/graphql/index.js:75545:41\n\n   75542 allProjects: async (_source, args, context) => {\n   75543   const take = args.take || 50;\n   75544   const skip = args.skip || 0;\n→  75545   return context.prisma.project.findMany(\n  The column `Project.lnurl_callback_url` does not exist in the current database.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allProjects"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "P2022",
          "clientVersion": "3.5.0",
          "meta": {
            "column": "Project.lnurl_callback_url"
          },
          "stacktrace": [
            "Error: ",
            "Invalid `context.prisma.project.findMany()` invocation in",
            "/var/task/functions/graphql/index.js:75545:41",
            "",
            "   75542 allProjects: async (_source, args, context) => {",
            "   75543   const take = args.take || 50;",
            "   75544   const skip = args.skip || 0;",
            "→  75545   return context.prisma.project.findMany(",
            "  The column `Project.lnurl_callback_url` does not exist in the current database.",
            "    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:38675:17)"
          ]
        }
      }
    }
  ],
  "data": null
}


so that's why I kept the old back-end url

@johnsBeharry 
do we have an updated version of the back-end server somewhere ??

**Comment by bumi** [comment]
Then the migrations might have not been executed. I could do that, so the `lnurl_callback_url` is now there.  

you can test the queries also from your browser: https://makers.bolt.fun/.netlify/functions/graphql

**Comment by MTG2000** [comment]
yeah, it's working now 👍👍
