### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by secondl1ght** [peakshift/makers.bolt.fun#16]
Do we have an asset we want to use for this?

**Comment by secondl1ght** [comment]
Nice, can I get permission to the Figma?

secondl1ght@protonmail.com

**Comment by barefoot-88** [comment]
Hmm let me check. Currently it's in a organisational figma file, Johns might be able to do it!

**Comment by johnsBeharry** [comment]
hey @secondl1ght @barefoot-88 I've updated the favicon for this site already could you test it https://makers.bolt.fun ? you might need to clear your cache.

**Comment by secondl1ght** [comment]
Favicon is working for me on makers.bolt.fun and bolt.fun/guide but not on the Hackathon page or the main bolt.fun page. @johnsBeharry so you will take care of the rest of the favicons then?

**Comment by johnsBeharry** [comment]
resolved in a recent update
