### ISSUE TITLE
Find a new Proxy service for validating lightning addresses

### ISSUE THREAD

**Issue by MTG2000** [peakshift/makers.bolt.fun#234]
The service that we have been using as a cors proxy (codetaps) isn't working properly anymore, we've been using this service to validate that a lightning address returns a response when a user input his lightning address in his profile settings.

For now, I removed the proxy, so only the ln servers that return cors headers will work for now.

I search for a free reliable service, but couldn't really find a good one.

So we might have to host our own or create a cloudflare worker that adds cors headers to some requests.

**Comment by johnsBeharry** [comment]
Deployed one on cloudflare workers. Seems to be working.
