### ISSUE TITLE
Add "Bitcoin Connect" as new project capability

### ISSUE THREAD

**Issue by MoritzKa** [peakshift/makers.bolt.fun#276]
If I create a project on bolt.fun I can add capabilities to it. 
![chrome_74cOGKx0Wo](https://github.com/peakshift/makers.bolt.fun/assets/13707997/b350b803-4d9c-4e0c-94cb-34cd2495fd05)

There have been quite powerful developments this year which many projects already support. 

I would like to add 1 new capability: 

Capability: Bitcoin Connect https://bitcoin-connect.com/
Logic:
- It is built on open standards (e.g. WebLN, Nostr Wallet Connect) to link lightning wallets with apps. 
- Users can connect any wallet and keep their trusted setup 
- App developers benefit from a single API to support several wallets at the same time. 

It cuts down complexity to integrate lightning payments substantially and ensures certain UX standards which is needed to bring more developers and users to lightning.

**Comment by MTG2000** [comment]
Thanks for the suggestion.
I added it.

I've used this emoji: 🔌 for it.
But if you have a better emoji, please let me know.
