### ISSUE TITLE
Question: Emojis vs Icons

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#34]
As seen in the recently designed page title elements (e.g Stories 🎙, Hackathons 🍿)... we are mixing and matching the use of emojis throughout the platform when it comes to category pills, page titles, etc. However, in the dropdown menu under Community section we are differentiating the pages visually using icons (similar to the emojis, but still a different style). 

So, the question is do we keep the icon styles we have or switch everything to emojis? It might be worth deciding now before this version is released and new pages are built out.

Here's a side by side comparison for you to visualise...

<img width="832" alt="Screenshot 2022-06-13 at 13 36 02" src="https://user-images.githubusercontent.com/36778205/173286653-7664e3b1-a2c4-4f53-ad98-2c485ae6f01c.png">

**_NOTE:_** We can keep the use of emojis in buttons or CTAs (e.g comment, save, share icons etc for actions)

If we decide to use the emojis, we should use the following ones for pages:

- Stories = 🎙
- Discussions = 💬
- Hackathons = 🍿 or 🏆
- Bounties = 🎯
- Grants = 💸

For categories...

- Design = 🎨
- Development = 💻
- Lightning = ⚡️
- WebLN = 🎛
- LNURL = 🚦

**Comment by johnsBeharry** [comment]
Stories should be ✍️ or 📝 as the mic can be used for podcasts (a type of story). The 🎙 makes "Stories" look like they are audio based.
