### ISSUE TITLE
Alby send payment not returning preimage of transaction

### ISSUE THREAD

**Issue by MTG2000** [peakshift/makers.bolt.fun#4]
Making a tip to a project consists of three steps:
1- Getting an invoice from the backend to the client
2- Confirming the invoice from client and sending it using a webln provider
3- sending the payment preimage to the backend after completion to confirm it.

But currently, it seems that paying invoices through alby provider is not returning a preimage variable, only "paymentHash" and "route"

**Comment by bumi** [comment]
this is a bug in Alby and will be fixed in the release coming in the next two days 
you could get around this by installing the latest development version: https://github.com/getAlby/lightning-browser-extension

**Comment by bumi** [comment]
would even be awesome if you could do that and confirm it works with the latest master

**Comment by MTG2000** [comment]
I tried it on firefox, but unfortunately, preimage is still returned as undefined :

![image](https://user-images.githubusercontent.com/50504183/150133512-49fd89a5-415a-4fd2-9674-af54133e655d.png)

( I installed the extension on firefox today, so it should be the latest version )

**Comment by bumi** [comment]
which node are you connected to?

**Comment by bumi** [comment]
yes. Lndhub. thanks.

hmm..
can you check if this demo works for you: https://codepen.io/bumibumi/pen/GRMzbwe is the `preimage` shown there? 
probably not, but I just try to debug this.

**Comment by MTG2000** [comment]
I'm not able to complete the transaction...
![image](https://user-images.githubusercontent.com/50504183/150201063-b3177e00-8e65-4264-b9df-b72e44e380a5.png)
