### ISSUE TITLE
Feature: Story tags 🏷

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#40]
**Problem**
Currently we only have 3 topics for Stories (bitcoin, lightning, gaming)

**Solution**
Let's create some more...

- 🎙 Podcast
- 💻 Workshop
- 🚦 Standup Report
- 🗓 Event

**Comment by MTG2000** [comment]
hmm
should we consider "Podcast" or "Workshop" to be a story's topic ???
I feel like they are more like a type or tag.
because for example, a story will be a podcast about gaming with lightning.
or about a Bitcoin event, and so on.

what do you think ??

**Comment by barefoot-88** [comment]
Hmm, I kind of agree, but if that's the case why do we have tags & topics? Aren't they kind of one and the same? @johnsBeharry care to enlighten us?

**Comment by MTG2000** [comment]
I'm myself more confused now... 😅
maybe the topic should be more like the category of the post, 
so it is one of: ( Finance, gaming, media & news, shopping, arts, ...etc)
& the tags can highlight what things are mentioned in the post, 
like: (bitcoin, lightning, lnurl, lnbits, podcast, event, course, ...etc)

**Comment by johnsBeharry** [comment]
It wasn't my decision to have tags, topics, and categories I think it's just something that came out of no design QA.

Categories of stories should be mapped to the ones in the products listing.

Tags/Topics perhaps we merge these two?

**Comment by barefoot-88** [comment]
Does categories actually make sense for stories in that case? Seems more useful to develop the topics feature. 

A story is very different from a product and might not fit into one of those categories, or more likely fits into more than one!

**Comment by MTG2000** [comment]
So you mean that there is no post's topic anymore, only tags ??

**Comment by johnsBeharry** [comment]
Been looking into how our main inspiration dev.to does it, and I've come up with this.

Given dev.to has multiple "post types" (post, question, listing, podcast, etc)
1. Tags are universal but are not necessarily always selectable in each post type. Listings for example only has #paid and #temp tags
2. Listings also has additional custom fields which can help with display and filtering (categories list, location, expiration date)
3. All post types seem to have tags
4. Some tags are "official" where they have a custom logo, description, colour, and posting/moderation guidelines
5. There is a podcast tag for posts but it doesn't change the way the post is displayed, there is a specific podcast post-type for that.

Conclusion:
1. This way dev.to is using is inline with solution 1 that @barefoot-88 posted. Extending the solution; the sidebar does not have to be dynamic, we can select some specific official tags to show here.
2. "Capabilities" were originally suggested to display on products as a technology lookup, which we could then create different directories from AND we can also generate some stats on the kinds of functionalities applications are adopting. Perhaps we can ignore this taxonomy for now though, it seems like something else that's not tags. More along the lines of "[built with](https://builtwith.com)" 
3. Should products also use tags?

**Comment by MTG2000** [comment]
so to close this discussion, what we reached is this:
- We don't have an independent "Topic" field, so I'll remove its table from the DB
- we will be using tags as the topics.
- users can create new tags
- but we will have some tags marked as "Official", & they will have an emoji associated with them.
- on the feed page, we will show a filter listing of the most used official tags.

**Comment by johnsBeharry** [comment]
Hey @barefoot-88 nice start to this list, gives us a good place to work from. Overall I'd say we start off with as little as possible. We have the posts from our YouTube, a few people from Qala that I've been reaching out to, MTGs article on lnurl-auth, and yours on authentication so I think we start from there and moderate the posts as more gets added. 

> ⚡️ Lightning
> 🪙 Bitcoin

The community is about lightning and bitcoin so not sure if these would be so relevant to tag.

> 🚦 Standups

What would be the purpose of this one? The PPP? Maybe merge with #products 

> 🚀 Product

A post connected to/about a product?

> 🍿 Workshop

As in a video of a workshop?

> ~~💸 Trading & Finance~~

I'd vote to have this one yet and don't really wanna attract too much trading content unless someone's making a trading app tutorial or something. We're in it for the tech :D 

> 🎓 Op-eds

What's this one for?

---

Lastly I think stylistically what do you think about hashtags with hyphens instead of spaces and non-alphabet symbols?

###### Technical Note: Stories + Tags + Nostr Distribution
When we post stories to nostr we should not include the tags as our own tag moderators would be able to update them on behalf of the author on our platform, but since they won't have the private keys won't be able to make the change on Nostr. This an interesting point to highlight on an architectural standpoint. The tagging data we would "own" as a platform so we can better improve discovery for everyone, but comments, the markdown of the post itself, 🔥 sats, would be owned by the private key holder.

**Comment by barefoot-88** [comment]
> 🚦 Standups
Purpose would be to generate a template that users could post their PPPs from. To get the ball rolling. I know eventually these will want to be done from the profile.

> 🚀 Product
Yup, if they're launching a product or just want to talk about something that is WIP they could attach a #product tag to it

> 🍿 Workshop
Perhaps workshop isn't the best word to use. But yeah, something like a course, video, or instructional content for others to learn from.

> 💸 Trading&Finance
Agreed. Could get cluttered with Chads discussing price movements.

> 🎓 Op(inion)-Ed(ucation)
My auth article would probably be considered an Op-Ed... perhaps 🔬 Research would be more appropriate...

**Comment by barefoot-88** [comment]
Great work on the deployment of tags @MTG2000 

Here are some UI notes:
- Are we using the # before the tag name (e.g #design). If so, should we put it in? Pls confirm @johnsBeharry 
- Please could we give the list-item / tag a padding of 4 pixels. This means that for the hover state, a padding of 4px should show around the around the edge. Currently it lies flush to the square (emoji) element and it looks a tad odd. 

**How it currently looks**
<img width="330" alt="Screenshot 2022-06-15 at 19 17 30" src="https://user-images.githubusercontent.com/36778205/173814858-432e5535-a78a-423d-947a-66775549e8c3.png">

**How it should look**
<img width="429" alt="Screenshot 2022-06-15 at 19 49 53" src="https://user-images.githubusercontent.com/36778205/173820395-c1ac69d7-7b25-4f92-92ae-c62f1e4fd3d2.png">

<img width="330" alt="Screenshot 2022-06-15 at 19 50 34" src="https://user-images.githubusercontent.com/36778205/173820487-79287298-c4d4-4a5a-88c4-faa8f37d4d13.png">

Figma link: https://www.figma.com/file/2rWlc79smZ9oyWSZHKhUUy/BOLT%F0%9F%94%A9FUN?node-id=1372%3A57337

**Comment by barefoot-88** [comment]
Also, for the dropdown menu. This is a great v1, good job. Do you think we can have the pre-text as:

"Add up to 5 tags. Search popular ones or add your own"

If the user has added 5 and this field is shown as disabled, we should say "Max. 5 tags reached. Remove a tag to add another."

<img width="867" alt="Screenshot 2022-06-15 at 19 52 55" src="https://user-images.githubusercontent.com/36778205/173820886-c2201032-9490-41d5-8399-64069a84e9c8.png">

We can review this components design fully at a later stage adn implement the error state as shown in the design, as opposed to disabling the field.
