### ISSUE TITLE
Implement a nostr based commenting system

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/makers.bolt.fun#57]
@fiatjaf has created a commenting widget after a discussion about the topic with him some weeks ago. It is built in react and is a great starting point for us to implement on stories. 

One of the limitations of this current widget is that it does not support threaded conversation, but I've learned that Nostr 

https://github.com/fiatjaf/nostr-comments-widget-react/blob/master/src/widget.jsx

- https://github.com/fiatjaf/nostr-comments-widget-react/issues/7
- https://github.com/fiatjaf/nostr-comments-widget-react/issues/4
- https://github.com/fiatjaf/nostr-comments-widget-react/issues/2

---

_The initial goal was to create something along the lines of Disqus, which we can still do but since we need comments first to be able to increase engagement on posts on the platform we can bookshelf it until we learn more about Nostr and how to go about creating this widget. There are some open issues in the repo which can help in that future planning._

**Comment by barefoot-88** [comment]
We should organise a call to review this feature, as well as some of the bugs that @MTG2000 has raised in the implementation of this feature.

**Comment by barefoot-88** [comment]
Fantastic work team! Esp. @MTG2000 !
