### ISSUE TITLE
Redesign the "Create new story" page

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#62]
### Issues
ATM, our "Create new story" has a few enhancements that could be made to it in order to improve the usability and general maker experience when creating a story.

- **Images:** currently users have to copy and paste an image url, preview it, then upload
- **Story title:** This doesn't feel prominent enough and should stand out more visually. 
- **Tags:** this still requires some focus and shouldn't lead to shitcoinery.
- **Error states:** currently the error states are shown beneath the individual items and there isn't any focus redirection to the user as the page remains stationary and doesn't move to + highlight the issues at hand.
- **Typography:** this requires some attention and should be clear to the user with regards to visual hierarchy (e.g avoid reusing Heading 1, only used for the Title). 

### Solutions

- **Images:** allow makers to upload a file/image from their local device, like any standard image uploader - rather than using URLs
- **Story title:** Preview this title in Heading 1 format and remove the "Create a story" heading above the card to improve user focus and visual hierarchy.
- **Tags:** Only allow users to select from a prepopulated selection of tags (that we choose), avoiding the issue of customised tags like "Ethereum". This update should also implement the tags dropdown component as it was designed, which includes emojis + descriptions.
- **Error states:** The error messages should be displayed at the top of the page (either in the centre or right-hand column) as one single message (i.e grouped errors), and the users attention should be brought to it by removing the scroll position and moving to the top of the page where the error message shows.
- **Typography:** ...

### Additional improvements
- **Story templates:** providing stock templates that users can choose from when creating a story (e.g Intro, product launch, standup report)
- **Saved drafts:** allowing users to save drafts of their stories that they can find later
- **Tagging products:** see issue #59  

**Empty**
<img width="766" alt="Screenshot 2022-07-07 at 18 11 32" src="https://user-images.githubusercontent.com/36778205/177831346-ea2eafff-f518-4426-b7a4-253add2e71f7.png">

**Error**
<img width="762" alt="Screenshot 2022-07-07 at 18 12 00" src="https://user-images.githubusercontent.com/36778205/177831420-09628eb3-35f8-4e05-8617-d633c1430e5b.png">

**Add tags**
<img width="758" alt="Screenshot 2022-07-07 at 18 12 38" src="https://user-images.githubusercontent.com/36778205/177831518-7a0bbf08-2831-4ef1-aa8b-a497f57e959d.png">

**Add product**
<img width="762" alt="Screenshot 2022-07-07 at 18 13 21" src="https://user-images.githubusercontent.com/36778205/177831678-ca6614b7-69ba-413f-9f48-6b9581d3a06d.png">

<img width="761" alt="Screenshot 2022-07-07 at 18 14 00" src="https://user-images.githubusercontent.com/36778205/177831745-8edf790d-b78a-4b0a-8cff-8e6b3f688ea9.png">

**Comment by johnsBeharry** [comment]
are we implementing project tagging as part of this sprint?
also referencing #67 as part of this project

**Comment by MTG2000** [comment]
Yes, I will implement the storing in local storage for the currently edited post.

But for the project tagging feature, I suggest that we do it in the next spring.
Cause it will require some work on the back-end, create-post-page, post-page, and probably the project-details-modal.

So before building it, we should probably in a meeting thoroughly discuss how this feature will work, and define the different specs.

**Comment by barefoot-88** [comment]
Agreed re. the project tagging, I think we should have a discussions about the enhancements/redesigns that will come to the projects sections.

**Comment by barefoot-88** [comment]
### Mobile
<img width="794" alt="Screenshot 2022-07-14 at 18 03 46" src="https://user-images.githubusercontent.com/36778205/179040763-88e50cd0-3f24-4830-8706-0681965a40b3.png">
