### ISSUE TITLE
Bring the user's attention to the form field that contains an error message

### ISSUE THREAD

**Issue by MTG2000** [peakshift/makers.bolt.fun#66]
When a user click submit on a form, an error message is shown below the input field, but this input field may be out of the viewport, so he may not notice it until he scrolls up.

Suggested solutions are:
1- show the error in a fixed banner at the top or in a side bar.
2- auto scroll to the first input from the top that contains the error message (I prefer this solution)
3- any other suggestions ??

**Comment by barefoot-88** [comment]
I'd suggest we use option 1 and auto-scroll to the top of the page which will show the error message + most likely show the input field which requires focus too (given that the user can see all Heading fields (title, tags, cover img) + the start of the markdown editor).
