### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by secondl1ght** [peakshift/makers.bolt.fun#7]
This screen is missing the asset `lightning-big.svg`, does someone have this that we can add?

![image](https://user-images.githubusercontent.com/85003930/152033907-d8db01fd-60a3-4b1d-a29d-da74426040be.png)

**Comment by secondl1ght** [comment]
Here's another one we need:

![image](https://user-images.githubusercontent.com/85003930/152034229-b059f8a7-bc54-41a6-afd1-b944ac533fbe.png)

**Comment by johnsBeharry** [comment]
this one has been resolved in the launch.
