### ISSUE TITLE
Redesign the Title field on "Create New Story" page

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#78]
Referenced in: https://github.com/peakshift/makers.bolt.fun/issues/62

### Issue
The current design of the Create New Story page doesn't feel prominent enough and should stand out more visually.

<img width="1219" alt="Screenshot 2022-07-12 at 11 18 19" src="https://user-images.githubusercontent.com/36778205/178468329-f7a04b37-3cac-4027-ab7c-664769713d71.png">

### Solution
Preview this title in Heading 1 format and remove the "Create a story" heading above the card to improve user focus and visual hierarchy.

<img width="595" alt="Screenshot 2022-07-12 at 11 18 55" src="https://user-images.githubusercontent.com/36778205/178468438-748fcec9-3a26-4fd2-9e33-d71d1dec2917.png">

**Comment by johnsBeharry** [comment]
@MTG2000 been looking at the new title field design on the [preview site](https://makers-bolt-fun-preview.netlify.app/blog/create-post) and noticed it doesn't wrap the text. One potential solution is to create an auto sizing (vertical) `<textarea>`

**Comment by barefoot-88** [comment]
### Mobile view
<img width="636" alt="Screenshot 2022-07-14 at 17 46 38" src="https://user-images.githubusercontent.com/36778205/179035217-92384ef7-f4e6-48a5-a387-c34dfc527781.png">
