### ISSUE TITLE
Improve the error states of "Create New Story" feature

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#80]
Referencing: https://github.com/peakshift/makers.bolt.fun/issues/62 & https://github.com/peakshift/makers.bolt.fun/issues/66

### Issue
Currently the error states are shown beneath the individual items and there isn't any focus redirection to the user as the page remains stationary and doesn't move to + highlight the issues at hand.

### Solution
The error messages should be displayed at the top of the page (either in the centre (mobile) or right-hand column (web)) as one single message (i.e grouped errors), and the users attention should be brought to it by removing the scroll position and moving to the top of the page where the error message shows.

All of the errors listed below would be seen within the device frame if the page scrolling position was redirected to the top. So we could "point" to the errors even further by highlighting the error section (e.g Title, tags, body copy, etc) by filling it with colour Error / 50, and then fading it to normal after 0.5 seconds. This would "highlight" the error with a colour tint. This is a UI enhancement and might not be necessary for V1.

<img width="1047" alt="Screenshot 2022-07-12 at 12 22 21" src="https://user-images.githubusercontent.com/36778205/178478790-3f6d4041-ba29-4fa9-8719-613f0473b1c4.png">

**Img size error**
This error should be shown at the time of upload, rather than after clicking "Publish"
<img width="631" alt="Screenshot 2022-07-12 at 12 15 21" src="https://user-images.githubusercontent.com/36778205/178477671-4246ae18-580f-4b33-a701-d0faa1788693.png">

**List of possible errors:**
- Image size too large
- Add story title
- Story title must be 2+ words
- Add at least one tag
- Post must contain at least 10+ words

**Comment by johnsBeharry** [comment]
There could also be network connectivity errors cc @MTG2000 could you chime in on what other errors can occur here?

**Comment by barefoot-88** [comment]
I think we can probably show all errors in the style of the red banner (errors card) shown above
