### ISSUE TITLE
Introduced Saved Drafts to "Create New Story" feature

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/makers.bolt.fun#82]
Reference: https://github.com/peakshift/makers.bolt.fun/issues/62

### Issue
Most blog editors/platforms will allow users to save drafts of their stories, so that they can edit them later on or come back and finish them at a later date.

### Solution
Introduce a "Save Draft" button next to Publish, allowing users to save the story as a draft so that they can edit/publish it later on. Once a draft has been saved, if it is changed any further, I suggest we possibly implement an auto-save feature that updates their Story draft.

### States
**Default / Empty**
This is the state the user sees when they have not yet saved their story as a draft.

<img width="1153" alt="Screenshot 2022-07-12 at 13 10 34" src="https://user-images.githubusercontent.com/36778205/178486613-4e7d0993-df9d-460e-b705-bb83840f2fac.png">

**Saving**
The "Save Draft" button should show a transitory state to show that the action of saving the draft is currently being taken and the action is loading.

<img width="1156" alt="Screenshot 2022-07-12 at 13 11 32" src="https://user-images.githubusercontent.com/36778205/178486767-5cc0a182-a887-4904-90f2-62edda039def.png">

**Success**
Once the users draft has successfully been saved, the button should momentarily be shown as a green success button to indicate the action has been completed. The user will also see their saved draft appear in their Saved Drafts card in the right-hand column, after a second or so this green button should revert back to Save Draft so the user can save any changes they may make.

<img width="1151" alt="Screenshot 2022-07-12 at 13 12 51" src="https://user-images.githubusercontent.com/36778205/178486980-0e9e0151-b715-47f0-ac5b-77f1680d5169.png">

**Error**
If for some reason there is an error (e.g network connect issue), we should show an error message next to the Save Draft button (if error, this button should show its default state, allowing the user to repeat the action). 

<img width="1149" alt="Screenshot 2022-07-12 at 13 15 18" src="https://user-images.githubusercontent.com/36778205/178487345-ef1a0e36-54b0-47e0-972a-09c0dc5cbfbd.png">

**Comment by johnsBeharry** [comment]
@barefoot-88
1. "delete draft" button should be red to signify it's a destructive action. 
2. the errors in this design don't conform to the error prompt shown in #80 was that on purpose?

**Comment by barefoot-88** [comment]
1. Agreed 
2. It was on purpose. The error felt to me like it was in a slightly different category compared to the story markdown errors. We could use the same style though. What were your thoughts on this?

**Comment by barefoot-88** [comment]
### Mobile view
<img width="851" alt="Screenshot 2022-07-14 at 18 11 43" src="https://user-images.githubusercontent.com/36778205/179042882-3beeb944-3db6-440e-8e00-cbd487ccc5e0.png">

**Comment by barefoot-88** [comment]
### Tasks
- Align Saved Drafts card with top of Edit story card
- Change "Delete draft" from Blue -> Red to signify destructive action.

<img width="1164" alt="Screenshot 2022-07-25 at 12 44 48" src="https://user-images.githubusercontent.com/36778205/180770369-bc6c1bcf-5aaa-422b-be71-3bdaa1334b71.png">

**Comment by barefoot-88** [comment]
## Task
Change "Delete draft" from Blue -> Red to signify destructive action. @MTG2000
